name: Deploy - PPRD

on:
  push:
    branches: [release]
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment-name: 'PreProduction'
      app-name: 'TU_APP_PPRD'
      build-definition: 'BackOfficePPRD'
      settings-var: ${{ vars.PPRD_JSON }}
      verify-url: 'https://TU_APP_PPRD.azurewebsites.net'
    secrets:
      publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PPRD }}
