name: Build and deploy ASP.Net Core app to Azure Web App - secihti-pprd

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Inject Configuration (PPRD_JSON)
        env:
          PPRD_JSON_CONTENT: ${{ vars.PPRD_JSON }}
        run: |
          if [ -n "$PPRD_JSON_CONTENT" ]; then
            echo "$PPRD_JSON_CONTENT" > appsettings.json
          else
            echo "La variable PPRD_JSON está vacía."
          fi

      - name: Build with dotnet
        run: dotnet build --configuration Release
        env:
          Build_DefinitionName: 'BackOfficePPRD'

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        env:
          Build_DefinitionName: 'BackOfficePPRD'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write 
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BCAA3C9D922444139B022FEDEBDB1B9C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_10BE6488BA8A4CAFBE0655683EB28924 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_22C62F578A6A4FD9942CCC56D15C80DC }}

      - name: Enable clean deploy (Run From Package)
        uses: azure/CLI@v2
        with:
          inlineScript: |
            RG=$(az webapp list --query "[?name=='secihti-pprd'].resourceGroup" -o tsv)
            # Primero leemos si ya tiene el valor asignado de despliegues previos
            CURRENT_VAL=$(az webapp config appsettings list -g $RG -n secihti-pprd --query "[?name=='WEBSITE_RUN_FROM_PACKAGE'].value" -o tsv)
            
            if [ "$CURRENT_VAL" != "1" ]; then
                echo "Activando modo despliegue limpio..."
                az webapp config appsettings set -g $RG -n secihti-pprd --settings WEBSITE_RUN_FROM_PACKAGE=1
                echo "Esperando 60 segundos a que Kudu se reinicie para evitar colisiones..."
                sleep 60
            else
                echo "El app service ya está en modo de despliegue limpio. No hay necesidad de reiniciarlo."
            fi

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'secihti-pprd'
          slot-name: 'Production'
          package: .
